### PR TITLE
ci-workflow: Add optinal access-token secret to ci-workflow.yml

### PR DESCRIPTION
**Pull request by kfollesdal**
Make it possible to access protected flakes for example flakes in private GitHub repos.

### CODE REVIEW

**Comment by rickynils** [comment]
@kfollesdal I have two concerns about this:

* Does this really add much over simply adding `access-tokens` to the `nix_conf` option yourself? We could perhaps add documentation for how to set it up?
* If you feel that having a separate option for this is motivated, can we come up with another name, perhaps `nix_access_tokens`? Otherwise this could be confused with access tokens for the nixbuild.net service.

**Comment by kfollesdal** [comment]
@rickynils, the intention with PR #18 where `nix_conf` got added was to use it for `access-tokens`. But I get error when trying to pass secrets to a reusable workflow if it is not defined in the secrets section in the workflow. For example if I try the following I get error: `Unrecognized named-value: 'secrets'` referencing to the `nix_conf` line. 
```
jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v14
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      nix_conf: "access-tokens = github.com=${{ secrets.GIT_TOKEN }}"
```
So it seems like it is only possible to use secrets in an reusable workflow if it is defined in the secrets section of the workflow. Maybe you know a way around this? Agree it is better to only have `nix_conf` and add `access-tokens` with `nix_conf` if it is possible.

**Comment by rickynils** [comment]
Ah, I see. I don't know a way around it, but I will try to research it a bit.

**Comment by rickynils** [comment]
@kfollesdal In `nix-quick-install-action`, a [github_access_token](https://github.com/nixbuild/nix-quick-install-action/blob/v24/action.yml#L28) setting was added in [v23/v24](https://github.com/nixbuild/nix-quick-install-action/releases/tag/v24). This setting has now, in [v18](https://github.com/nixbuild/nixbuild-action/releases/tag/v18) also been exposed in the [ci-workflow](https://github.com/nixbuild/nixbuild-action/blob/v18/.github/workflows/ci-workflow.yml#L37). Does this fix your issue, or would you also need a general `access_tokens` setting?

**Comment by kfollesdal** [comment]
@rickynils thanks I think that will solve my problem. Thanks 😊

**Pull request closed without merging**
